platform: linux

image_resource:
  type: registry-image
  source: { repository: hashicorp/packer, tag: full } # https://github.com/concourse/registry-image-resource

inputs:
  - name: concourse-pipelines

outputs:
  - name: packer-images

run:
  path: /bin/sh
  args:
    - -c
    - |
      cd concourse-pipelines/projects/packer-demo
      packer build vsphere_builds.json 